version: "3.8"

services:
  mongo-db:
    image: "mongo"
    restart: always
    container_name: "mongo-db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: s3cr3t0
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
